// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QUICK_INVENTORY.Data;

#nullable disable

namespace QUICK_INVENTORY.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241112121902_CorreccionesParaProductoMovimiento")]
    partial class CorreccionesParaProductoMovimiento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QUICK_INVENTORY.Domain.IdentidadRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("QUICK_INVENTORY.Domain.IdentidadUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("QUICK_INVENTORY.Domain.InventarioCorte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEdita")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioAltaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEditaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEliminaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioAltaId");

                    b.HasIndex("UsuarioEditaId");

                    b.HasIndex("UsuarioEliminaId");

                    b.ToTable("InventarioCorte");
                });

            modelBuilder.Entity("QUICK_INVENTORY.Domain.InventarioCorteDetalle", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("InventarioCorteId")
                        .HasColumnType("int");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEdita")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<int>("StockFinal")
                        .HasColumnType("int");

                    b.Property<int>("StockInicial")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioAltaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEditaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEliminaId")
                        .HasColumnType("int");

                    b.HasKey("ProductoId", "InventarioCorteId");

                    b.HasIndex("InventarioCorteId");

                    b.HasIndex("UsuarioAltaId");

                    b.HasIndex("UsuarioEditaId");

                    b.HasIndex("UsuarioEliminaId");

                    b.ToTable("InventarioCorteDetalle");
                });

            modelBuilder.Entity("QUICK_INVENTORY.Domain.MovimientoTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEdita")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioAltaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEditaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEliminaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioAltaId");

                    b.HasIndex("UsuarioEditaId");

                    b.HasIndex("UsuarioEliminaId");

                    b.ToTable("MovimientoTipos");
                });

            modelBuilder.Entity("QUICK_INVENTORY.Domain.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEdita")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<string>("Locacion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("StockMaximo")
                        .HasColumnType("int");

                    b.Property<int>("StockMedidaId")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioAltaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEditaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEliminaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockMedidaId");

                    b.HasIndex("UsuarioAltaId");

                    b.HasIndex("UsuarioEditaId");

                    b.HasIndex("UsuarioEliminaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("QUICK_INVENTORY.Domain.ProductoMovimiento", b =>
                {
                    b.Property<int>("Folio")
                        .HasColumnType("int");

                    b.Property<int>("MovimientoTipoId")
                        .HasColumnType("int");

                    b.Property<string>("Empleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEdita")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroExterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroInterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioAltaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEditaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEliminaId")
                        .HasColumnType("int");

                    b.HasKey("Folio", "MovimientoTipoId");

                    b.HasIndex("MovimientoTipoId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioAltaId");

                    b.HasIndex("UsuarioEditaId");

                    b.HasIndex("UsuarioEliminaId");

                    b.ToTable("ProductoMovimientos");
                });

            modelBuilder.Entity("QUICK_INVENTORY.Domain.StockMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEdita")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioAltaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEditaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEliminaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioAltaId");

                    b.HasIndex("UsuarioEditaId");

                    b.HasIndex("UsuarioEliminaId");

                    b.ToTable("StockMedidas");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("QUICK_INVENTORY.Domain.IdentidadRol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("QUICK_INVENTORY.Domain.IdentidadUsuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("QUICK_INVENTORY.Domain.IdentidadUsuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("QUICK_INVENTORY.Domain.IdentidadRol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QUICK_INVENTORY.Domain.IdentidadUsuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("QUICK_INVENTORY.Domain.IdentidadUsuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QUICK_INVENTORY.Domain.InventarioCorte", b =>
                {
                    b.HasOne("QUICK_INVENTORY.Domain.IdentidadUsuario", "UsuarioAlta")
                        .WithMany()
                        .HasForeignKey("UsuarioAltaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QUICK_INVENTORY.Domain.IdentidadUsuario", "UsuarioEdita")
                        .WithMany()
                        .HasForeignKey("UsuarioEditaId");

                    b.HasOne("QUICK_INVENTORY.Domain.IdentidadUsuario", "UsuarioElimina")
                        .WithMany()
                        .HasForeignKey("UsuarioEliminaId");

                    b.Navigation("UsuarioAlta");

                    b.Navigation("UsuarioEdita");

                    b.Navigation("UsuarioElimina");
                });

            modelBuilder.Entity("QUICK_INVENTORY.Domain.InventarioCorteDetalle", b =>
                {
                    b.HasOne("QUICK_INVENTORY.Domain.InventarioCorte", "InventarioCorte")
                        .WithMany("Detalles")
                        .HasForeignKey("InventarioCorteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QUICK_INVENTORY.Domain.Producto", "Producto")
                        .WithMany("InventarioCortes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QUICK_INVENTORY.Domain.IdentidadUsuario", "UsuarioAlta")
                        .WithMany()
                        .HasForeignKey("UsuarioAltaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QUICK_INVENTORY.Domain.IdentidadUsuario", "UsuarioEdita")
                        .WithMany()
                        .HasForeignKey("UsuarioEditaId");

                    b.HasOne("QUICK_INVENTORY.Domain.IdentidadUsuario", "UsuarioElimina")
                        .WithMany()
                        .HasForeignKey("UsuarioEliminaId");

                    b.Navigation("InventarioCorte");

                    b.Navigation("Producto");

                    b.Navigation("UsuarioAlta");

                    b.Navigation("UsuarioEdita");

                    b.Navigation("UsuarioElimina");
                });

            modelBuilder.Entity("QUICK_INVENTORY.Domain.MovimientoTipo", b =>
                {
                    b.HasOne("QUICK_INVENTORY.Domain.IdentidadUsuario", "UsuarioAlta")
                        .WithMany()
                        .HasForeignKey("UsuarioAltaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QUICK_INVENTORY.Domain.IdentidadUsuario", "UsuarioEdita")
                        .WithMany()
                        .HasForeignKey("UsuarioEditaId");

                    b.HasOne("QUICK_INVENTORY.Domain.IdentidadUsuario", "UsuarioElimina")
                        .WithMany()
                        .HasForeignKey("UsuarioEliminaId");

                    b.Navigation("UsuarioAlta");

                    b.Navigation("UsuarioEdita");

                    b.Navigation("UsuarioElimina");
                });

            modelBuilder.Entity("QUICK_INVENTORY.Domain.Producto", b =>
                {
                    b.HasOne("QUICK_INVENTORY.Domain.StockMedida", "StockMedida")
                        .WithMany("Productos")
                        .HasForeignKey("StockMedidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QUICK_INVENTORY.Domain.IdentidadUsuario", "UsuarioAlta")
                        .WithMany()
                        .HasForeignKey("UsuarioAltaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QUICK_INVENTORY.Domain.IdentidadUsuario", "UsuarioEdita")
                        .WithMany()
                        .HasForeignKey("UsuarioEditaId");

                    b.HasOne("QUICK_INVENTORY.Domain.IdentidadUsuario", "UsuarioElimina")
                        .WithMany()
                        .HasForeignKey("UsuarioEliminaId");

                    b.Navigation("StockMedida");

                    b.Navigation("UsuarioAlta");

                    b.Navigation("UsuarioEdita");

                    b.Navigation("UsuarioElimina");
                });

            modelBuilder.Entity("QUICK_INVENTORY.Domain.ProductoMovimiento", b =>
                {
                    b.HasOne("QUICK_INVENTORY.Domain.MovimientoTipo", "RegistroTipo")
                        .WithMany("Registros")
                        .HasForeignKey("MovimientoTipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QUICK_INVENTORY.Domain.Producto", "Producto")
                        .WithMany("Registros")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QUICK_INVENTORY.Domain.IdentidadUsuario", "UsuarioAlta")
                        .WithMany()
                        .HasForeignKey("UsuarioAltaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QUICK_INVENTORY.Domain.IdentidadUsuario", "UsuarioEdita")
                        .WithMany()
                        .HasForeignKey("UsuarioEditaId");

                    b.HasOne("QUICK_INVENTORY.Domain.IdentidadUsuario", "UsuarioElimina")
                        .WithMany()
                        .HasForeignKey("UsuarioEliminaId");

                    b.Navigation("Producto");

                    b.Navigation("RegistroTipo");

                    b.Navigation("UsuarioAlta");

                    b.Navigation("UsuarioEdita");

                    b.Navigation("UsuarioElimina");
                });

            modelBuilder.Entity("QUICK_INVENTORY.Domain.StockMedida", b =>
                {
                    b.HasOne("QUICK_INVENTORY.Domain.IdentidadUsuario", "UsuarioAlta")
                        .WithMany()
                        .HasForeignKey("UsuarioAltaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QUICK_INVENTORY.Domain.IdentidadUsuario", "UsuarioEdita")
                        .WithMany()
                        .HasForeignKey("UsuarioEditaId");

                    b.HasOne("QUICK_INVENTORY.Domain.IdentidadUsuario", "UsuarioElimina")
                        .WithMany()
                        .HasForeignKey("UsuarioEliminaId");

                    b.Navigation("UsuarioAlta");

                    b.Navigation("UsuarioEdita");

                    b.Navigation("UsuarioElimina");
                });

            modelBuilder.Entity("QUICK_INVENTORY.Domain.InventarioCorte", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("QUICK_INVENTORY.Domain.MovimientoTipo", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("QUICK_INVENTORY.Domain.Producto", b =>
                {
                    b.Navigation("InventarioCortes");

                    b.Navigation("Registros");
                });

            modelBuilder.Entity("QUICK_INVENTORY.Domain.StockMedida", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
